# TIME CONFIG
# This is the number of seconds before it attempts to start the event.
# If event can't be started, the event will end
# ___________________
# BROADCAST-TIMES CONFIG
#These are the list of times that would be broadcasted till event starts. For example, "60 seconds till the event starts!", "30 seconds till the event starts"
#Must follow this format exactly. NO SPACES! USE DOUBLE QUOTES
# ____________________
#EVENT-END-COMMANDS CONFIG
# list of commands that will be executed when an event ends
# NO SLASH
# %player% = a player in the event. Ex: "spawn %player%"" will send all players from the event to spawn



player-limit-ffa: 50
player-limit-waterdrop: 50
player-limit-sumo1v1: 50
player-limit-sumo2v2: 50
player-limit-sumo4v4: 80
player-limit-islandclash: 24
player-limit-temperature: 50

time: 60

broadcast-times: "60,30,15,10,5,4,3,2,1"

event-end-commands:
- "spawn %player%"
- "anothercommand %player%"

ffa-startLoc: "null"
islandclash-startLoc: "null"
waterdrop-starLoc: "null"
temperature-startLoc: "null"
sumo-startLoc: "null"

waterdrop-corner1: "null"
waterdrop-corner2: "null"


temperature-corner1: "null"
temperature-corner2: "null"

spectator-spawn: 
  ffa: "null"
  waterdrop: "null"
  sumo: "null"
  islandclash: "null"
  temperature: "null"