player-limit-ffa: 50
player-limit-waterdrop: 50
player-limit-sumo1v1: 50
player-limit-sumo2v2: 50
player-limit-sumo4v4: 80
player-limit-islandclash: 24
player-limit-temperature: 50
# This is the number of seconds before it attempts to start the event.
# If event can't be started, the event will end
time: 60
#These are the list of times that would be broadcasted till event starts. For example, "60 seconds till the event starts!", "30 seconds till the event starts"
#Must follow this format exactly. NO SPACES! USE DOUBLE QUOTES
broadcast-times: "60,30,15,10,5,4,3,2,1"
# list of commands that will be executed when an event ends
# NO SLASH
# %player% = a player in the event. Ex: "spawn %player%"" will send all players from the event to spawn
event-end-commands:
- "spawn %player%"

# the location where all players will spawn when the FFA event starts
ffa-startLoc: null

spectator-spawn:
  ffa: null
  waterdrop: null
  sumo: null
  islandclash: null
  temperature: null